version: '4.1'

services:
  db:
    container_name: pg_db
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    hostname: postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    hostname: pgadmin
